### PR TITLE
Add some infrastructure to support auth0 logins

### PR DESCRIPTION
**Pull request by djmitche**
For taskcluster/taskcluster#547.  This is just WIP, really.

One thing I'd like here is to figure out how the overall set of login strategies could be configured flexibly.  So most dev environments could just have `export TF_VAR_login_strategies="[]"`, but an environment that wanted to support Github would have `export TF_VAR_login_strategies='[{"strategy":"github", "clientId": "..", "clientSecret": ".."}]'`.  That would then get reflected into both tc-ui's configuration and tc-web-server's configuration.

### CODE REVIEW

**Comment by helfi92** [comment]
Is the following expected:

Screen Shot 2019-04-30 at 1 48 31 PM

**Comment by djmitche** [comment]
Sort of -- it's just updated to use the latest version of the monorepo as a submodule, which has lots of other, unrelated changes

**Comment by djmitche** [comment]
https://github.com/taskcluster/taskcluster/issues/672 would be a way to simplify this..

**Review by imbstack — APPROVED** [review]
Looks reasonable to me. We've definitely woven a complicated web w.r.t. configuring our services.

**Review by helfi92 — APPROVED** [review]

**Pull request merged**
